name: ubuntu-single-user-nix-inside-podman

services:
  ubuntu-single-user-nix-inside-podman:
    container_name: ubuntu-single-user-nix-inside-podman
    hostname: ubuntu-single-user-nix-inside-podman
    build:
      context: .
      args:
        # 具有 /nix 权限的用户
        USER_NAME: ubuntu
        USER_PASSWORD: 123456
    systemd: true
    pids_limit: 131072
    restart: unless-stopped
    ports:
      # 转发 SSH 服务，如果需要监听所有网卡，使用 "57307:22"
      - "127.0.0.1:57307:22"
    devices:
      - "/dev/kvm:/dev/kvm"
    group_add:
      - keep-groups
    volumes:
      - home:/home
      - nix:/nix

volumes:
  home:
  nix:
