services:
  ubuntu-single-user-nix-inside-podman:
    container_name: ${CONTAINER_NAME:-ubuntu-single-user-nix-inside-podman}
    build:
      context: .
      args:
        USER_NAME: ${USER_NAME:-ubuntu}
        USER_PASSWORD: ${USER_PASSWORD:-123456}
    systemd: true
    restart: unless-stopped
    ports:
      - "127.0.0.1:${SSH_PORT:-57307}:22"
      # 如果需要监听所有网卡
      # - "${SSH_PORT:-57307}:22"
    volumes:
      - home:/home
      - nix:/nix

volumes:
  home:
  nix:
